### ISSUE TITLE
Single cell analysis performance with worse results

### ISSUE THREAD

**Issue by daichengxin** [bigbio/quantms#287] opened 2023-09-19 09:35 UTC
### Description of the bug

Analyzing single cell dataset [PXD016291](https://www.ebi.ac.uk/pride/archive/projects/PXD016921). The results folder can be found in [here](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-benchmark/PXD016921-MBR/). The MBR is enabled. The results looks quite different from original paper. The less proteins are quantified in single cell samples than original results. And more proteins are misquantified in blank sample than original results. The original paper used MaxQuant with as follows parameters: 

> All raw files were processed using MaxQuant (version 1.6.3.3) for feature detection, database searching, and protein/peptide quantification. MS/MS spectra were searched against the UniProtKB/Swiss-Prot human database (downloaded on October 26, 2018, containing 20 397 reviewed sequences). N-Terminal protein acetylation and methionine oxidation were selected as variable modifications. Carbamidomethylation of cysteine residues was set as a fixed modification. The peptide mass tolerances of the first search and main search (recalibrated) were <30 and 5 ppm, respectively. The minimum peptide length was six amino acids, and the maximum peptide mass was 4600 Da. Only two missed cleavages were allowed for each peptide. The second peptide search was activated to identify coeluting and cofragmented peptides from one MS/MS spectrum. Both peptides and proteins were filtered with a maximum false discovery rate (FDR) of 0.01. The MBR feature with a matching window of 0.7 min and an alignment window of 20 min, was activated. Label-free quantitation (LFQ) calculations were performed separately in each parameter group containing similar cell loadings. Both unique and razor peptides were selected for protein quantification. Other unmentioned parameters were the MaxQuant default settings. Potential contaminants and reverse sequences were filtered out.

![QQ截图20230919173108](https://github.com/bigbio/quantms/assets/37200167/1cabaf37-acaa-4c54-9784-19bf7c5b7eaa)

### Command used and terminal output

```console
$ nextflow run /hps/nobackup/juan/pride/reanalysis/quantms/main.nf -c /hps/nobackup/juan/pride/reanalysis/quantms/nextflow.config -profile ebislurm --input PXD016921-MBR.sdrf.tsv --search_engines comet,msgf --root_folder /hps/nobackup/juan/pride/reanalysis/single-cell/PXD016921/ --local_input_type raw --outdir PXD016921-MBR --database /hps/nobackup/juan/pride/reanalysis/multiomics-configs/databases/Homo-sapiens-uniprot-reviewed-contaminants-decoy-202210.fasta --protein_level_fdr_cutoff 0.01 --psm_level_fdr_cutoff 0.01 --quantify_decoys true --transfer_ids mean --targeted_only false --skip_post_msstats false --enable_pmultiqc true -resume
```

### Relevant files

[Original MaxQuant results](https://ftp.pride.ebi.ac.uk/pride/data/archive/2020/02/PXD016921/MQsearchresults_Single_cell.zip)
[quantms results](http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-benchmark/PXD016921-MBR/)

**Comment by ypriverol** [comment] 2023-09-19 09:38
@daichengxin can you add some description about How the data was analyzed with MaxQuant and the original paper.

**Comment by jpfeuffer** [comment] 2023-09-19 10:43
Thank you for the analysis. Very interesting. Can we maybe run the analysis with looser FDR cutoffs to see if it's more an identification problem or a quantification problem?

**Comment by ypriverol** [comment] 2023-09-19 12:06
@jpfeuffer a couple of ideas: 

In single cell, looks for me that MBR would be doing most of the job for the single cell runs. If you see we ID most of the peptides in the 20 and 100 samples (complex samples), more than MQ. Those samples are used as "channels" to look for poor signals from the single cell files. My point is the following: 

> The MBR feature with a matching window of 0.7 min and an alignment window of 20 min, was activated.

Do you think this 20 min window that they use for MBR in MQ can be the difference with us? 

Do you think we need to do something in the experimental design.? For the MBR we are annotating every sample as a biological replicate to enable MBRs.

**Comment by jpfeuffer** [comment] 2023-09-19 12:21
Yes, of we find out that it's not the identification performance we will check quantification.
But if you have only 100 proteins that pass FDR, you cannot quantify more than that and it is useless to check quantification.

**Comment by daichengxin** [comment] 2023-09-19 13:55
More than half of the unique peptides originated with the MBR. 
![image](https://github.com/bigbio/quantms/assets/37200167/a303d1c5-6656-408b-a69a-e200cfccfcb6)

**Comment by ypriverol** [comment] 2023-09-19 14:09
This is what I thought, see @jpfeuffer The majority of peptides are not coming from IDs but from the MBR, then we should see how we fail to do proper MBR in our side, my previous two comments.

**Comment by jpfeuffer** [comment] 2023-09-19 14:31
Still.. if they don't pass FDR, there is nothing to quantify. So we have to wait for the ID analysis

**Comment by daichengxin** [comment] 2023-09-21 02:55
Almost all of the peptides quantified only in MQ are from MBR. However, for quantms, these peptides also are only quantified in other files rather than from same file. it suggest we fail to do proper MBR, right?

![image](https://github.com/bigbio/quantms/assets/37200167/e52725ce-de11-45d1-ad2b-51b02bbc2c27)
![image](https://github.com/bigbio/quantms/assets/37200167/87bc8ce6-1ee7-4745-8ed4-5f3f342f030c)
![image](https://github.com/bigbio/quantms/assets/37200167/ebf2d7d6-d112-411f-b0a5-f859bbf998f2)
![image](https://github.com/bigbio/quantms/assets/37200167/2c420476-4aa2-4297-a438-ec8841c5ee06)

**Comment by jpfeuffer** [comment] 2023-09-21 06:27
Can you please add the command you used?

**Comment by daichengxin** [comment] 2023-09-21 06:43
`nextflow run /hps/nobackup/juan/pride/reanalysis/quantms/main.nf -c /hps/nobackup/juan/pride/reanalysis/quantms/nextflow.config -profile ebislurm --input PXD016921-MBR.sdrf.tsv --search_engines comet,msgf --root_folder /hps/nobackup/juan/pride/reanalysis/single-cell/PXD016921/ --local_input_type raw --outdir PXD016921-MBR --database /hps/nobackup/juan/pride/reanalysis/multiomics-configs/databases/Homo-sapiens-uniprot-reviewed-contaminants-decoy-202210.fasta --protein_level_fdr_cutoff 0.01 --psm_level_fdr_cutoff 0.01 --quantify_decoys true --transfer_ids mean --targeted_only false --skip_post_msstats false --enable_pmultiqc true -resume` @jpfeuffer

**Comment by jpfeuffer** [comment] 2023-09-21 06:48
I don't know. I can't see any signs of transfer in the Proteomicslfq logs.
Do you have the call to proteomicslfq?

**Comment by ypriverol** [comment] 2023-09-21 07:22
The command with the relapsed FDR is: 
```
nextflow run /hps/nobackup/juan/pride/reanalysis/quantms/main.nf -c /hps/nobackup/juan/pride/reanalysis/quantms/nextflow.config -profile ebislurm --input PXD016921-MBR.sdrf.tsv --search_engines comet,msgf --root_folder /hps/nobackup/juan/pride/reanalysis/single-cell/PXD016921/ --local_input_type raw --outdir PXD016921-MBR --database /hps/nobackup/juan/pride/reanalysis/multiomics-configs/databases/Homo-sapiens-uniprot-reviewed-contaminants-decoy-202210.fasta --protein_level_fdr_cutoff 0.15 --psm_level_fdr_cutoff 0.15 --quantify_decoys true --transfer_ids mean --targeted_only false --skip_post_msstats false --enable_pmultiqc true -resume
```
Here the results: http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-benchmark/PXD016921-MBR/

**Comment by jpfeuffer** [comment] 2023-09-21 07:29
I found the plfq command. Looks correct.
One thing is, that we only transfer_ids if they occur in more than 50% of the samples. I don't know how MQ does it.

**Comment by daichengxin** [comment] 2023-09-21 07:31
@jpfeuffer @ypriverol ran the data with a more relaxed FDR 0.15 at Protein and PSM level. However, the number of quantified peptides did not increase significantly. Similarily, almost all of the peptides quantified only in MQ are from MBR. For quantms, these peptides also are only quantified in other files rather than from same file. 
![image](https://github.com/bigbio/quantms/assets/37200167/29346a3d-d8b2-42fe-8044-143bb1bffd37)

**Comment by jpfeuffer** [comment] 2023-09-21 07:36
I think if we loosen this we should think about an FDR approach for transferred quantification first.
E.g. shifted decoy EICs

**Comment by jpfeuffer** [comment] 2023-09-21 08:19
You can use the new container tomorrow to play around with a parameter that controls this proportion.
You need to expose it quickly in the pipeline.

**Comment by ypriverol** [comment] 2023-09-21 08:26
Can you let me know what is the parameter that we will need to use.

**Comment by jpfeuffer** [comment] 2023-09-21 08:29
id_transfer_threshold

**Comment by ypriverol** [comment] 2023-09-21 08:30
What is the default value?

**Comment by ypriverol** [comment] 2023-09-25 15:29
@timosachsenberg @jpfeuffer @daichengxin I ran again the data with the same parameters but now with `id_transfer_threshold` as `0.10` I don't see any improvements in the results. Can you double check @daichengxin?

**Comment by daichengxin** [comment] 2023-09-26 13:04
Wow! The number os unique peptides and proteins have increased a lot. But false positives have also increased. Further adjustment of id_transfer_threshold may be needed? 

![image](https://github.com/bigbio/quantms/assets/37200167/a808e2bc-c6bf-47d1-9fde-e81abdf5aa81)

**Comment by ypriverol** [comment] 2023-09-26 13:07
Can you add the False positives and the MaxQuant results in the table?

**Comment by ypriverol** [comment] 2023-09-26 13:18
> To be honest, without FDR control the settings we can do will not be detailed enough. Sure you could require at least two samples with IDs but it will always pick up everything in the blank sample even if the correlation etc is complete trash.

I know, I want to see how much False positives do we have when moving over some thresholds.

Do you have an idea about which kind of algorithm we can implement to really control the FDR for this type of experiment?

**Comment by timosachsenberg** [comment] 2023-09-27 10:34
The runs have quite a big alignment error for some masses. I will take a look at the consensusXML. Maybe if we apply stricter RT filtering on transferred quants, we already get rid of those false/spurious links from the blank sample.
```
Alignment based on:
- 46 data points for sample 1 (1 outliers removed)
- 2252 data points for sample 2 (14 outliers removed)
- 2123 data points for sample 3 (11 outliers removed)
- 1249 data points for sample 4 (1893 outliers removed)
- 4306 data points for sample 5 (117 outliers removed)
- 6816 data points for sample 6 (488 outliers removed)
- 4305 data points for sample 7 (2784 outliers removed)

Calculating RT linking tolerance bins...
RT_bin_start, Tolerance
58.4147, 242.107
1638.33, 276.325
...
6957.7, 2461.47
6976.28, 2292.36
6998.41, 1087.48
7032.68, 1632.92
7057.85, 2193.84
7076.39, 2258.63
7098.71, 2085.63
7119.56, 2266.9
7151.04, 1172.92
7170.17, 1165.37
7191.98, 1126.44
```

**Comment by timosachsenberg** [comment] 2023-09-27 10:45
Is it possible to get the consensusXML output @daichengxin ? I want to take a look at the intensity and RT deviation distribution of the blank

**Comment by ypriverol** [comment] 2023-09-27 10:48
http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-benchmark/PXD016921-MBR/proteomicslfq/PXD016921-MBR.sdrf_openms_design_openms.consensusXML

**Comment by jpfeuffer** [comment] 2023-09-27 11:19
In my experience a higher deviation is normal towards the end of the RT.
But yes sure they are even higher in this sample.
Unfortunately usually you don't have a known blank to tweak this so an FDR approach is desperately needed.
How do we set the linking tolerance again?

What about reactivating the SVM scoring of FFID as a first step?

**Comment by timosachsenberg** [comment] 2023-09-27 11:41
> In my experience a higher deviation is normal towards the end of the RT. But yes sure they are even higher in this sample. Unfortunately usually you don't have a known blank to tweak this so an FDR approach is desperately needed. How do we set the linking tolerance again?
> 

AFAIK based on the maximum difference observed.

> What about reactivating the SVM scoring of FFID as a first step?

It is worth a try, but I don't know what the best way is (e.g., it is pairwise). Maybe we can meet and discuss this a bit in more detail.

**Comment by timosachsenberg** [comment] 2023-09-27 11:57
Ok I see the need for FDR filtering but intensity-wise most of the found features (about 97%) in the blank are at the noise level.

**Comment by jpfeuffer** [comment] 2023-09-27 12:39
Is there an SNR value for our features?

**Comment by jpfeuffer** [comment] 2023-09-27 15:06
I can only think of decoy strategies :) calculate SNRs for decoys and target. Use IDPEP or better a non-parameteric version of it. In the simplest form, just use a probability cutoff.

**Comment by daichengxin** [comment] 2023-10-06 09:23
Wow! Here are new results after major changes in the code of openms for MBR.

![image](https://github.com/bigbio/quantms/assets/37200167/d91ac04a-6209-4ebd-a543-5373e3ae6f6d)

**Comment by jpfeuffer** [comment] 2023-10-06 10:31
Cool. The ratios look good. Which SVM probability cutoff was used? Can you try multiple?

**Comment by ypriverol** [comment] 2023-10-06 11:30
feature_with_id_min_score = 0.25
    feature_without_id_min_score = 0.75

https://github.com/bigbio/quantms/blob/06b9529abf10a65ee3753ea14c5fee248aa39564/nextflow.config#L158

**Comment by timosachsenberg** [comment] 2023-10-06 14:50
@daichengxin how do you count the peptides?
I did some quick check:
```
cut -d',' -f 2,11 notransfer_1.0_1000_star.csv | sort | uniq | grep Blank | wc -l
cut -d',' -f 2,11 notransfer_1.0_1000_star.csv | sort | uniq | grep Singlecell2 | wc -l
cut -d',' -f 2,11 notransfer_1.0_1000_star.csv | sort | uniq | grep Singlecell3 | wc -l
cut -d',' -f 2,11 notransfer_1.0_1000_star.csv | sort | uniq | grep Singlecell4 | wc -l
cut -d',' -f 2,11 notransfer_1.0_1000_star.csv | sort | uniq | grep 20HeLa | wc -l
cut -d',' -f 2,11 notransfer_1.0_1000_star.csv | sort | uniq | grep 100HeLa | wc -l

98
3877
3208
3082
4612
9042
11513
```

These numbers seem a bit higher.
Even if I do ```| grep -v "(" | ``` to filter out modified I get way higher numbers.

What am I doing differently?

**Comment by daichengxin** [comment] 2023-10-06 15:08
I used the msstats_in file, removed the modification and only counted the `unique peptides`.

**Comment by timosachsenberg** [comment] 2023-10-06 15:29
like 
```
cut -d',' -f 2,11 msstats.csv |  sed 's/([^)]*)//g' | sort | uniq | grep Singlecell4 | wc -l
```
?
Do you have a command?

**Comment by jpfeuffer** [comment] 2023-10-07 12:48
I think he means unique as in "unique for a protein".

**Comment by jpfeuffer** [comment] 2023-10-07 13:11
You need to check what MQ exports and how it defines uniqueness if you want to compare by #identifications. You can check by picking some of the group-unique peptides and see how MQ defines them.
Ideally one would just compare the number of features with an ID though. I have no idea if you can do that with MQ.

**Comment by daichengxin** [comment] 2023-10-07 13:16
Here is my script. And i try to run @timosachsenberg  command, but got different values from @timosachsenberg. 

```
def sub_mod(peptide):
    peptide = peptide.replace(".", "")
    peptide = re.sub(r"\(.*?\)", "", peptide)
    return peptide

quantms = pd.read_csv("./PXD016921MBRnewSVM/PXD016921-MBR.sdrf_openms_design_msstats_in.csv", sep=',', header=0)
quantms = quantms[-quantms['ProteinName'].str.contains("DECOY_|CONTAMINANT_|REV_|BOVIN")]
quantms["sequence"] = quantms.apply(lambda x: sub_mod(x["PeptideSequence"]), axis=1)
msstats_in_data = quantms.groupby('sequence').filter(lambda x: len(set(x["ProteinName"])) == 1)
print(quantms.groupby("Reference")["sequence"].nunique())
print(quantms.groupby("Reference")["ProteinName"].nunique())
```
![image](https://github.com/bigbio/quantms/assets/37200167/78766545-aa0d-412e-bc33-aa26c0ec8f83)

**Comment by jpfeuffer** [comment] 2023-10-07 13:19
How is your MQ script?
And can we put the MQ data next to the quantms results for both UPS and this one?

**Comment by daichengxin** [comment] 2023-10-07 14:28
```
MQ = pd.read_csv("./MQsearchresults_Single_cell/txt/peptides.txt", sep="\t")
# MQ = MQ[(MQ["Reverse"] != "+")& (MQ["Potential contaminant"] != "+") & (MQ["Unique (Groups)"] == "yes")]
MQ = MQ[(MQ["Reverse"] != "+")& (MQ["Potential contaminant"] != "+")]
print(MQ[-MQ["Identification type Single cell 1"].isna()]["Sequence"].nunique())
print(MQ[-MQ["Identification type Single cell 2"].isna()]["Sequence"].nunique())
print(MQ[-MQ["Identification type Single cell 3"].isna()]["Sequence"].nunique())
print(MQ[-MQ["Identification type Single cell 4"].isna()]["Sequence"].nunique())

MQ = pd.read_csv("./MQsearchresults_Single_cell/txt/proteinGroups.txt", sep="\t")
MQ = MQ[(MQ["Reverse"] != "+")& (MQ["Potential contaminant"] != "+")]
# MQ = MQ[MQ["Unique peptides"] > 0]
print(MQ[-MQ["Identification type Single cell 1"].isna()]["Protein IDs"].nunique())
print(MQ[-MQ["Identification type Single cell 2"].isna()]["Protein IDs"].nunique())
print(MQ[-MQ["Identification type Single cell 3"].isna()]["Protein IDs"].nunique())
print(MQ[-MQ["Identification type Single cell 4"].isna()]["Protein IDs"].nunique())
print(MQ[-MQ["Identification type Blank"].isna()]["Protein IDs"].nunique())
print(MQ[-MQ["Identification type 20 HeLa cells"].isna()]["Protein IDs"].nunique())
print(MQ[-MQ["Identification type 100 HeLa cells"].isna()]["Protein IDs"].nunique())


```

**Comment by daichengxin** [comment] 2023-10-07 15:30
0.1&0.9 results. Results folder: http://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-benchmark/PXD016921-MBR-newSVM/

![image](https://github.com/bigbio/quantms/assets/37200167/07247520-76a6-443c-858a-5fa550e49048)

**Comment by jpfeuffer** [comment] 2023-10-07 16:23
I think if you wanted more IDs, one should have used 0.1 and something that is less than 0.75, e.g. 0.5

**Comment by jpfeuffer** [comment] 2023-10-07 16:26
> ```
> MQ = pd.read_csv("./MQsearchresults_Single_cell/txt/peptides.txt", sep="\t")
> # MQ = MQ[(MQ["Reverse"] != "+")& (MQ["Potential contaminant"] != "+") & (MQ["Unique (Groups)"] == "yes")]
> MQ = MQ[(MQ["Reverse"] != "+")& (MQ["Potential contaminant"] != "+")]
> print(MQ[-MQ["Identification type Single cell 1"].isna()]["Sequence"].nunique())
> print(MQ[-MQ["Identification type Single cell 2"].isna()]["Sequence"].nunique())
> print(MQ[-MQ["Identification type Single cell 3"].isna()]["Sequence"].nunique())
> print(MQ[-MQ["Identification type Single cell 4"].isna()]["Sequence"].nunique())
> 
> MQ = pd.read_csv("./MQsearchresults_Single_cell/txt/proteinGroups.txt", sep="\t")
> MQ = MQ[(MQ["Reverse"] != "+")& (MQ["Potential contaminant"] != "+")]
> # MQ = MQ[MQ["Unique peptides"] > 0]
> print(MQ[-MQ["Identification type Single cell 1"].isna()]["Protein IDs"].nunique())
> print(MQ[-MQ["Identification type Single cell 2"].isna()]["Protein IDs"].nunique())
> print(MQ[-MQ["Identification type Single cell 3"].isna()]["Protein IDs"].nunique())
> print(MQ[-MQ["Identification type Single cell 4"].isna()]["Protein IDs"].nunique())
> print(MQ[-MQ["Identification type Blank"].isna()]["Protein IDs"].nunique())
> print(MQ[-MQ["Identification type 20 HeLa cells"].isna()]["Protein IDs"].nunique())
> print(MQ[-MQ["Identification type 100 HeLa cells"].isna()]["Protein IDs"].nunique())
> 
> 
> ```

Why did you comment the filter for Unique (groups)?
This sounded like the right way to compare to our results.

**Comment by daichengxin** [comment] 2023-10-08 07:48
filtered results (unique for protein groups) @jpfeuffer 

![image](https://github.com/bigbio/quantms/assets/37200167/91c55fc5-b231-4147-8cf9-44ebeda02113)

**Comment by jpfeuffer** [comment] 2023-10-08 09:40
Ok can we compare it with different cutoffs now? Especially something lower than 0.9.

And without `.filter(lambda x: len(set(x["ProteinName"])) == 1)` for the quantms results.

**Comment by jpfeuffer** [comment] 2023-10-08 09:41
I don't think we need to compare protein groups for now. They will always be less if the peptides are less.

**Comment by timosachsenberg** [comment] 2023-10-08 10:31
> Here is my script. And i try to run @timosachsenberg command, but got different values from @timosachsenberg.

This is interesting. I used the old id files that Yasset provided in the original analysis and ran them through the ProteomicsLFQ tool. I got numbers much closer to MQ. I am currently traveling but would like to dig into the exact parameters used a bit more.

**Comment by daichengxin** [comment] 2023-10-08 11:09
![image](https://github.com/bigbio/quantms/assets/37200167/87c5dadb-2494-40a6-90ee-e1313e64760a)

**Comment by jpfeuffer** [comment] 2023-10-08 12:24
Thank you very much for the quick table. Surprisingly very few changes. This must mean that all unidentified Features have scores either below 0.6 or above 0.9.
Maybe an FDR approach is really really needed

**Comment by jpfeuffer** [comment] 2023-10-08 12:36
@timosachsenberg exact parameters are always visible in the pipeline_info folder

**Comment by timosachsenberg** [comment] 2023-10-09 06:44
That's the command I used. FDR settings seem the be the same. Do you see anything I missed?
 
```
/ceph/ibmi/abi/projects/sachsenb/OpenMS/openms-build/bin/ProteomicsLFQ \
-in Blank.mzML Singlecell1.mzML Singlecell2.mzML Singlecell3.mzML Singlecell4.mzML 20HeLacells.mzML 100HeLacells.mzML \
-ids Blank_consensus_fdr_filter.idXML Singlecell1_consensus_fdr_filter.idXML Singlecell2_consensus_fdr_filter.idXML Singlecell3_consensus_fdr_filter.idXML Singlecell4_consensus_fdr_filter.idXML 20HeLacells_consensus_fdr_filter.idXML 100HeLacells_consensus_fdr_filter.idXML \
    -design PXD016921-MBR.sdrf_openms_design.tsv \
    -out_cxml notransfer_1.0_1000_star.consensusXML \
    -out_msstats notransfer_1.0_1000_star.csv \
    -out notransfer_1.0_1000_star.mzTab \
    -fasta Homo-sapiens-uniprot-reviewed-contaminants-decoy-202210.fasta \
    -threads 40 \
    -Seeding:intThreshold 1000.0 \
    -protein_inference aggregation \
    -quantification_method feature_intensity \
    -feature_with_id_min_score 0.25 \
    -feature_without_id_min_score 0.75 \
    -targeted_only false \
    -mass_recalibration false \
    -protein_quantification unique_peptides \
    -alignment_order star \
    -PeptideQuantification:quantify_decoys \
    -psmFDR 0.01 \
    -proteinFDR 0.01 \
    -picked_proteinFDR true \
    2>&1 | tee notransfer_1.0_1000_star.txt
```

**Comment by jpfeuffer** [comment] 2023-10-09 06:54
No, looks the same as the 0.25_0.75 directory.
@timosachsenberg can you maybe download the Msstats file and run your command on your computer?

**Comment by jpfeuffer** [comment] 2023-10-09 06:55
Maybe the idxmls changed meanwhile? Changes in Sage or percolator adapter? No idea.

**Comment by timosachsenberg** [comment] 2023-10-09 07:57
> No, looks the same as the 0.25_0.75 directory. @timosachsenberg can you maybe download the Msstats file and run your command on your computer?
> 
> https://ftp.pride.ebi.ac.uk/pub/databases/pride/resources/proteomes/quantms-benchmark/PXD016921-MBR-newSVM-0.25-0.75/proteomicslfq/

I can confirm that these outputs match the ones Dai reported. Will now check if -Seeding:intThreshold 1000.0  makes such a difference.

**Comment by ypriverol** [comment] 2023-10-09 08:02
It looks like we are using the default parameter for `-Seeding:intThreshold`. Our command now for proteomicsLFQ is: 

```
    ProteomicsLFQ \\
        -threads ${task.cpus} \\
        -in ${mzml_sorted.join(' ')} \\
        -ids ${id_sorted.join(' ')} \\
        -design ${expdes} \\
        -fasta ${fasta} \\
        -protein_inference ${params.protein_inference_method} \\
        -quantification_method ${params.quantification_method} \\
        -targeted_only ${params.targeted_only} \\
        ${feature_with_id_min_score} \\
        ${feature_without_id_min_score} \\
        -mass_recalibration ${params.mass_recalibration} \\
        -protein_quantification ${params.protein_quant} \\
        -alignment_order ${params.alignment_order} \\
        ${decoys_present} \\
        -psmFDR ${params.psm_level_fdr_cutoff} \\
        -proteinFDR ${params.protein_level_fdr_cutoff} \\
        -picked_proteinFDR ${params.picked_fdr} \\
        -out_cxml ${expdes.baseName}_openms.consensusXML \\
        -out ${expdes.baseName}_openms.mzTab \\
        ${msstats_present} \\
        ${triqler_present} \\
        $args \\
        2>&1 | tee proteomicslfq.log
```

**Comment by timosachsenberg** [comment] 2023-10-09 08:54
Yep, main reason seems to be the intensity threshold.

**Comment by jpfeuffer** [comment] 2023-10-10 06:44
Numbers look really good. I wonder if MQ has a min. feature ity. cutoff.

I guess we need to see the effect on UPS

**Comment by daichengxin** [comment] 2023-10-10 08:10
1000 intensity threshold:

![image](https://github.com/bigbio/quantms/assets/37200167/b094d47f-7f8c-4bf9-88c6-f02928d2ed02)

**Comment by ypriverol** [comment] 2023-10-10 08:18
Looks like the rigth parameters are close to 0.20 - 0.80. @jpfeuffer @timosachsenberg

**Comment by ypriverol** [comment] 2023-10-13 08:55
I will close the current issue in favor of #303 . All discussions about MBR LFQ must be move to that issue.

**Closed by ypriverol** 2023-10-13 08:55 UTC
Labels: enhancement, help wanted, question, high-priority
